In [1]:
import torch

In [2]:
checkpoint = torch.load('../datasets/mass-base-uncased/mass-base-uncased.pt')

In [6]:
checkpoint

OrderedDict([('encoder.version', tensor([3.], device='cuda:0')),
             ('encoder.embed_tokens.weight',
              tensor([[-5.3830e-04, -6.0206e-02, -3.4619e-02,  ..., -1.6784e-02,
                       -4.4355e-02, -4.8423e-03],
                      [-1.6683e-03, -5.8929e-02, -3.9122e-02,  ..., -1.4526e-02,
                       -4.6738e-02, -6.0673e-03],
                      [-7.7320e-03, -6.1191e-02, -3.9913e-02,  ..., -1.4056e-02,
                       -4.8252e-02,  7.6896e-05],
                      ...,
                      [-8.1670e-02, -1.7845e-02, -6.9434e-02,  ...,  1.2783e-01,
                       -3.4474e-02,  8.2875e-02],
                      [-1.0377e-01, -8.8492e-03,  4.0887e-02,  ...,  1.2926e-01,
                       -2.1360e-02, -2.4281e-02],
                      [ 5.8865e-02, -9.9851e-02,  2.9467e-02,  ...,  1.6625e-02,
                        1.6109e-02,  8.4868e-02]], device='cuda:0')),
             ('encoder.embed_positions.weight',
         

In [3]:
exec(open("../deps/MASS/MASS-summarization/mass/bert_dictionary.py").read())


In [39]:
d = BertDictionary.load_from_file('../datasets/cnndm/dict.src.txt')

class TranslationMASSTask(TranslationTask):
    def __init__(self, args, src_dict, tgt_dict):
        super().__init__(args, src_dict, tgt_dict)

    @classmethod
    def load_dictionary(cls, filename):
        return BertDictionary.load_from_file(filename)

    def max_positions(self):
        """Return the max sentence length allowed by the task."""
        return self.args.max_source_positions, self.args.max_target_positions

In [38]:
exec(open("../deps/MASS/MASS-summarization/mass/translation.py").read())

ModuleNotFoundError: No module named '__main__.bert_dictionary'; '__main__' is not a package

TypeError: __init__() missing 1 required positional argument: 'args'

In [29]:
import argparse
args = 7
args.data='../datasets/cnndm/'
args.left_pad_source=False
args.left_pad_target=False
t.setup_task(args=args)

AttributeError: 'object' object has no attribute 'data'

In [19]:
t.load_dataset('test')

AttributeError: 'NoneType' object has no attribute 'data'

In [48]:
import argparse

args = argparse.Namespace()

args.data = '../datasets/cnndm/'
args.source_lang = 'src'
args.target_lang = 'tgt'
args.left_pad_source=False
args.left_pad_target=False
args.max_source_positions = 512
args.max_target_positions = 512
args.upsample_primary = 1
args.dataset_impl = None

t = TranslationMASSTask.setup_task(args)

| [src] dictionary: 30522 types
| [tgt] dictionary: 30522 types


In [49]:
t.load_dataset('test', epoch=0)

| loaded 11490 examples from: ../datasets/cnndm/test.src-tgt.src
| loaded 11490 examples from: ../datasets/cnndm/test.src-tgt.tgt
| ../datasets/cnndm/ test src-tgt 11490 examples


In [45]:
os.path.join('../datasets/cnndm/', '{}.{}-{}.{}'.format('test', 'src', 'tgt', 'src'))

'../datasets/cnndm/test.src-tgt.src'

In [50]:
d = t.dataset('test')

In [55]:
d[0]['source']


tensor([16766,  1010,  2605,  1011,  1048, 15185,  1011, 13229,  1011, 25269,
         2497,  1011,  1996,  2413, 12478,  2877,  2019,  4812,  2046,  1996,
         5823,  1997,  2446,  9328,  2015,  3462,  5345, 17788,  7278,  9317,
         2008,  2002,  2001,  2025,  5204,  1997,  2151,  2678,  8333,  2013,
         2006,  2604,  1996,  4946,  1012, 16766, 12478,  7987,  6610,  5863,
         2409, 13229,  2008,  1036,  1036,  2061,  2521,  2053,  6876,  2020,
         2109,  1999,  1996,  5823,  4812,  1012,  1005,  1005,  2002,  2794,
         1010,  1036,  1036,  1037,  2711,  2040,  2038,  2107,  1037,  2678,
         3791,  2000,  3202,  2507,  2009,  2000,  1996, 14766,  1012,  1005,
         1005,  5863,  1005,  1055,  7928,  3582,  4447,  2011,  2048,  7298,
         1010,  2446,  3679, 12170,  6392,  1998,  2413,  3000,  2674,  1010,
         1997,  1037,  3526,  3042,  2678,  4760,  1996, 24560,  2075,  2345,
         3823,  2013,  2006,  2604,  2446,  9328,  2015,  3462, 

In [59]:
d.src_dict[999]

'!'

In [77]:

' '.join([d.src_dict[q.item()] for q in d[10]['source']])


"- l ##rb - cnn - rr ##b - he ' s a blue chip college basketball recruit . she ' s a high school freshman with down syndrome . at first glance trey moses and ellie meredith could n ' t be more different . but all that changed thursday when trey asked ellie to be his prom date . trey - - a star on eastern high school ' s basketball team in louisville , kentucky , who ' s headed to play college ball next year at ball state - - was originally going to take his girlfriend to eastern ' s prom . so why is he taking ellie instead ? ` ` she ' s great . . . she listen ##s and she ' s easy to talk to ' ' he said . trey made the prom - po ##sal - l ##rb - yes , that ' s what they are calling invites to prom these days - rr ##b - in the gym during ellie ' s p . e . class . tri ##na he ##lson , a teacher at eastern , alerted the school ' s newspaper staff to the prom - po ##sal and posted photos of trey and ellie on twitter that have gone viral . she was n ' t sur ##pr ##iste ##d by trey ' s action

In [83]:
eos_index = d.src_dict.eos_index
bos_index = d.src_dict.bos_index

In [90]:
d.src_dict[1012]

'.'

In [91]:
' '.join([d.src_dict[q.item()] for q in d[10]['target']])

"college - bound basketball star asks girl with down syndrome to high school prom . pictures of the two during the ` ` prom - po ##sal ' ' have gone viral . [SEP]"

In [94]:
' PAD '.join(['a', 'b'])

'a PAD b'

In [96]:
 x = torch.randn(10)

In [97]:
x

tensor([-0.8697,  1.9066,  0.3178, -0.2502,  0.4459, -0.7611, -2.1835, -0.5411,
         0.0074,  0.7384])

In [104]:
torch.cumsum(d[10]['source'].eq(1012),dim=0)

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  7,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 11,
        11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 13, 13, 13, 13, 13, 13, 

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [109]:
mask = d[10]['source'].eq(1012).int()
mask


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [113]:
(torch.cumsum(mask, dim=0).type_as(mask) * mask).long() + 1012

tensor([1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1013, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1014, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1015, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1016, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1017, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1018, 1019, 1020, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1021, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 10

In [114]:
from pytorch_transformers import BertTokenizer

In [130]:
bpe = BertTokenizer.from_pretrained('bert-base-uncased')
bpe.do_basic_tokenize = False

In [131]:
bpe._tokenize('[CLS] museum : anne frank died earlier than previously believed . [SEP] researchers re-examined archives and testimonies of survivors . [SEP] anne and older sister margot frank are believed to have died in february 1945 . [SEP]')

['[CLS]',
 'museum',
 ':',
 'anne',
 'frank',
 'died',
 'earlier',
 'than',
 'previously',
 'believed',
 '.',
 '[SEP]',
 'researchers',
 're',
 '##-',
 '##ex',
 '##amine',
 '##d',
 'archives',
 'and',
 'test',
 '##imo',
 '##nies',
 'of',
 'survivors',
 '.',
 '[SEP]',
 'anne',
 'and',
 'older',
 'sister',
 'margot',
 'frank',
 'are',
 'believed',
 'to',
 'have',
 'died',
 'in',
 'february',
 '1945',
 '.',
 '[SEP]']

In [128]:
bpe.do_basic_tokenize = True
bpe._tokenize('[CLS] museum : anne frank died earlier than previously believed . [SEP] researchers re-examined archives and testimonies of survivors . [SEP] anne and older sister margot frank are believed to have died in february 1945 . [SEP]')

['[',
 '[UNK]',
 ']',
 'museum',
 ':',
 'anne',
 'frank',
 'died',
 'earlier',
 'than',
 'previously',
 'believed',
 '.',
 '[',
 '[UNK]',
 ']',
 'researchers',
 're',
 '-',
 'examined',
 'archives',
 'and',
 'test',
 '##imo',
 '##nies',
 'of',
 'survivors',
 '.',
 '[',
 '[UNK]',
 ']',
 'anne',
 'and',
 'older',
 'sister',
 'margot',
 'frank',
 'are',
 'believed',
 'to',
 'have',
 'died',
 'in',
 'february',
 '1945',
 '.',
 '[',
 '[UNK]',
 ']']

In [134]:
pad_idx = 10
eos_idx = 20

sent = torch.tensor([10, 10, 10, 10, 10, 5, 6, 7, 20, 8, 9, 4, 20, 30, 30, 30, 20])

In [163]:
sent

tensor([10, 10, 10, 10, 10,  5,  6,  7, 20,  8,  9,  4, 20, 30, 30, 30, 20])

In [160]:
mask = sent.ne(pad_idx)
keep = sent.eq(pad_idx)

In [162]:
mask

tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [138]:
(torch.cumsum(mask, dim=0).type_as(mask) * mask).long() + pad_idx

tensor([10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

tensor([ 0,  0,  0,  0,  0,  5,  6,  7, 20,  8,  9,  4, 20, 30, 30, 30, 20],
       dtype=torch.int32)

In [161]:
pos = (torch.cumsum((sent.type_as(mask) * mask).eq(eos_idx), dim=0).t + pad_idx + mask).long()

RuntimeError: expected type torch.LongTensor but got torch.IntTensor

In [157]:
mask + pos

tensor([10, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14],
       dtype=torch.int32)

In [166]:
def make_sentence_positions(tensor, padding_idx, eos_idx):
    mask = tensor.ne(padding_idx).int()
    return (
        torch.cumsum((tensor.type_as(mask) * mask).eq(eos_idx), dim=0).type_as(mask) + mask 
    ).long() + padding_idx




In [167]:
make_sentence_positions(sent, pad_idx, eos_idx)

tensor([10, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14])