In [1]:
import torch

In [2]:
checkpoint = torch.load('../datasets/mass-base-uncased/mass-base-uncased.pt')

In [6]:
checkpoint

OrderedDict([('encoder.version', tensor([3.], device='cuda:0')),
             ('encoder.embed_tokens.weight',
              tensor([[-5.3830e-04, -6.0206e-02, -3.4619e-02,  ..., -1.6784e-02,
                       -4.4355e-02, -4.8423e-03],
                      [-1.6683e-03, -5.8929e-02, -3.9122e-02,  ..., -1.4526e-02,
                       -4.6738e-02, -6.0673e-03],
                      [-7.7320e-03, -6.1191e-02, -3.9913e-02,  ..., -1.4056e-02,
                       -4.8252e-02,  7.6896e-05],
                      ...,
                      [-8.1670e-02, -1.7845e-02, -6.9434e-02,  ...,  1.2783e-01,
                       -3.4474e-02,  8.2875e-02],
                      [-1.0377e-01, -8.8492e-03,  4.0887e-02,  ...,  1.2926e-01,
                       -2.1360e-02, -2.4281e-02],
                      [ 5.8865e-02, -9.9851e-02,  2.9467e-02,  ...,  1.6625e-02,
                        1.6109e-02,  8.4868e-02]], device='cuda:0')),
             ('encoder.embed_positions.weight',
         

In [7]:
exec(open("../deps/MASS/MASS-summarization/mass/bert_dictionary.py").read())


In [6]:
d = BertDictionary.load_from_file('../datasets/cnndm/dict.src.txt')

class TranslationMASSTask(TranslationTask):
    def __init__(self, args, src_dict, tgt_dict):
        super().__init__(args, src_dict, tgt_dict)

    @classmethod
    def load_dictionary(cls, filename):
        return BertDictionary.load_from_file(filename)

    def max_positions(self):
        """Return the max sentence length allowed by the task."""
        return self.args.max_source_positions, self.args.max_target_positions

In [5]:
exec(open("../deps/MASS/MASS-summarization/mass/translation.py").read())

ModuleNotFoundError: No module named '__main__.bert_dictionary'; '__main__' is not a package

TypeError: __init__() missing 1 required positional argument: 'args'

In [7]:
import argparse
args = 7
args.data='../datasets/cnndm/'
args.left_pad_source=False
args.left_pad_target=False
t.setup_task(args=args)

AttributeError: 'int' object has no attribute 'data'

In [8]:
t.load_dataset('test')

NameError: name 't' is not defined

In [8]:
import argparse

args = argparse.Namespace()

args.data = '../datasets/cnndm/'
args.source_lang = 'src'
args.target_lang = 'tgt'
args.left_pad_source=False
args.left_pad_target=False
args.max_source_positions = 512
args.max_target_positions = 512
args.upsample_primary = 1
args.dataset_impl = None

t = TranslationMASSTask.setup_task(args)

| [src] dictionary: 30522 types
| [tgt] dictionary: 30522 types


In [9]:
t.load_dataset('train', epoch=0)

../datasets/cnndm/train.src-tgt.src
| loaded 287113 examples from: ../datasets/cnndm/train.src-tgt.src
| loaded 287113 examples from: ../datasets/cnndm/train.src-tgt.tgt
| ../datasets/cnndm/ train src-tgt 287113 examples


In [45]:
os.path.join('../datasets/cnndm/', '{}.{}-{}.{}'.format('test', 'src', 'tgt', 'src'))

'../datasets/cnndm/test.src-tgt.src'

In [10]:
d = t.dataset('train')

In [26]:
m = 0
c = 0
for q in d.src:
    c+= 1
    m = max(len(q), m)
    if len(q) == 509:
        print(' '.join([d.src_dict[t.item()] for t in q]))


- l ##rb - cnn - rr ##b - - - georgian leaders may be blaming russia for the conflict raging in south os ##set ##ia , but former soviet president mikhail go ##rba ##chev said thursday ` ` there is no doubt ' ' that georgia provoked the clash . mikhail go ##rba ##chev told cnn ' s larry king that russia called extra troops into georgia to stem violence . go ##rba ##chev told cnn ' s larry king that russia moved additional forces into south os ##set ##ia in response to ` ` devastation ' ' in the south os ##set ##ia city of ts ##kh ##in ##val ##i . ` ` this was the use of sophisticated weapons against a small town , against a sleeping people . this was a bar ##bari ##c assault , ' ' said go ##rba ##chev , the last president of the former soviet union . but georgian president mi ##kh ##eil sa ##aka ##sh ##vili , who also appeared on cnn ' s ` ` larry king live ' ' thursday , said he was ` ` profoundly shocked ' ' that mikhail go ##rba ##chev would use a television appearance ` ` for basica

- l ##rb - cnn - rr ##b - - - top seed maria sha ##ra ##po ##va made a surprise exit from the wta paris open when she was beaten in the quarterfinals friday by german ninth seed angel ##ique ke ##rber . sha ##ra ##po ##va had beaten ke ##rber in straight sets on the way to the final of the australian open last month , but was below her best as he slumped to a 6 - 4 6 - 4 defeat in the pierre de co ##uber ##tin indoor arena . the russian was playing her first tournament since losing to new world no . 1 victoria az ##are ##nka in the title match at the opening grand slam of the year . she came through her first match and will rise to no . 2 in the world rankings next week , but despite breaking ke ##rber ' s service twice in the opening set lost control of the match . world no . 27 ke ##rber broke back twice to forge a 5 - 4 lead and sha ##ra ##po ##va made two un ##force ##d errors to hand her the set . sha ##ra ##po ##va was also erratic in the second set , again giving up an early bre

- l ##rb - cnn - rr ##b - - - what has jay len ##o done lately for nbc in late night ? well , even the network ' s official wednesday announcement of his ou ##ster - l ##rb - in spring 2014 - rr ##b - acknowledges that ` ` the tonight show ' ' under len ##o ' s reign continues to rank no . 1 in both total viewers and ad ##vert ##iser - prized 18 - to - 49 - year - olds . that ' s against abc ' s recently relocated ` ` jimmy kim ##mel live ! ' ' as well as cbs ' long ##standing ` ` late show with david letterman , ' ' according to nielsen media research . nonetheless , nbc will be pushing him out for a second time , with ` ` late night ' ' host jimmy fallon taking over ` ` in conjunction ' ' with the network ' s coverage of next year ' s winter olympic games from soc ##hi , russia - l ##rb - scheduled to run from february 7 - 23 - rr ##b - . nbc universal ceo steve burke says in a statement that ` ` we are purpose ##fully making this change when jay is no . 1 , just as jay replaced john

elbow beach , bermuda - l ##rb - cnn - rr ##b - - - winds and rain associated with hurricane igor lashed bermuda on sunday ahead of the storm ' s arrival , forecast ##ers said , as the island braced for a potential direct hit . the official weather - observing site on bermuda reported sustained winds of 54 mph - l ##rb - 87 k ##ph - rr ##b - with a gust to 67 mph - l ##rb - 107 k ##ph - rr ##b - , the national hurricane center said . a gust of 89 mph - l ##rb - 143 k ##ph - rr ##b - was earlier reported at an elevated observation site . as of 8 p . m . et sunday , igor ' s center was about 60 miles - l ##rb - 95 kilometers - rr ##b - west - southwest of bermuda and moving north at about 14 mph - l ##rb - 22 k ##ph - rr ##b - . the storm was a category 1 hurricane , with maximum sustained winds of 75 mph - l ##rb - 120 k ##ph - rr ##b - , and forecast ##ers said its intensity was not expected to dim ##ini ##sh before it approached bermuda . igor was also very large , forecast ##ers said

by . kerry mcqueen ##ey . published : . 11 : 56 est , 27 april 2012 . | . updated : . 14 : 35 est , 27 april 2012 . after spending most of their lives in . human care , this was the day three or ##ang ##uta ##ns re ##ac ##qua ##int ##ed themselves . with the place they once called home . tentatively exploring their new . surroundings , the animals ' apprehension was soon replaced with curiosity . and a playful first moments of freedom . casey , les ##an and mali were the first . or ##ang ##uta ##ns to be returned to the wild in indonesia for almost a decade . after going through a rehabilitation programme in borneo . first moments of freedom : casey re ##ac ##qua ##int ##s herself with the rainforest as she is released into the wild ##s of ke ##h ##je se ##wen forest of mount bela ##h , in east kali ##man ##tan , indonesia . a swinging time : eight - year - olds les ##an - l ##rb - left - rr ##b - and mali - l ##rb - right - rr ##b - play in the trees of the sam ##bo ##ja lest ##ari re

by . quentin let ##ts . published : . 21 : 22 est , 16 july 2013 . | . updated : . 21 : 22 est , 16 july 2013 . shouting : chi ##we ##tel e ##ji ##of ##or is a powerful actor and he does look pass ##ably like the real patrice lu ##mum ##ba . director joe wright reduces to si ##llin ##ess a rather sim ##pl ##istic play about the politics of congo in its first years after independence from belgium in 1960 . chi ##we ##tel e ##ji ##of ##or stars as the republic ' s first prime minister , patrice lu ##mum ##ba . mr e ##ji ##of ##or is a powerful actor and he does look pass ##ably like the real lu ##mum ##ba . but need he shout so much ? could he not give us a more nu ##ance ##d idea of the cunning any nas ##cent democrat must possess ? daniel ka ##lu ##uy ##a plays joseph mob ##ut ##u , the one - time ac ##ol ##yte of lu ##mum ##ba who became his colonel - - and his nemesis . we see little subtle ##ty here , none of the cold ##ness or char ##ism ##a the real mob ##ut ##u must have had . th

by . margot peppers . nigerian and cameroon ##ian pop star den ##cia has hit out at lu ##pit ##a ny ##ong ' o for her new contract with lan ##com ##e , accusing her of bowing to ` white people companies ' . in an angry t ##wee ##t directed at the 12 years a slave star , she wrote : ` oh @ lu ##pit ##a _ ny ##ong ##o cl n ' t talk ab ##t the b ##lea ##ching cream ##s white people - l ##rb - companies - rr ##b - make cu ##z the white man pays her , they own her ! ! - l ##sb - sic - rs ##b - ' . the comment comes just a month after miss ny ##ong ' o mentioned den ##cia - who has been accused of marketing her own brand of skin - b ##lea ##ching cream called white ##nic ##ious - in a speech about learning to value the color of her own skin . scroll down for video . butt ##ing heads : nigerian and cameroon ##ian pop star den ##cia has hit out at lu ##pit ##a ny ##ong ' o for her new contract with lan ##com ##e , accusing her of bowing to ` white people companies ' fighting words : in a t ##w

by . marianne power . g ##wyn ##eth swear ##s by it , jennifer an ##isto ##n ca n ' t go a day without it and beyonce wants to tell the world about its benefits . no , it ' s not a new exercise regime or anti - age ##ing cream - it ' s a vegetable . ka ##le , to be exact . yes , this humble green leaf - a close relative of bro ##cco ##li and brussels sp ##rou ##ts - is the latest must - have product for the a - list , who are baking it , ju ##icing it , slicing it and even wearing ka ##le - slogan ##ed sweat ##suit ##s , and it looks like we ' re all following suit . marks & spencer says sales of ka ##le are already up a third on the same period last year , while at wait ##rose they ' re up 20 per cent . meanwhile , ka ##le is appearing on beauty shelves and a cook ##book called fifty shades of ka ##le has just been published . scroll down for video . marianne power - l ##rb - pictured - rr ##b - tries the cult of ka ##le . it ' s cheap , too - with a supermarket bag costing just # 1 -

brendan rodgers has branded criticism of ra ##hee ##m sterling as ` incredible ' as he prepares to un ##lea ##sh the england international on arsenal . during an unusually brief and tense press conference at liverpool ' s mel ##wood training ground , rodgers was economical with his words but his longest answer was saved for when the subject of sterling arose . the 20 - year - old scored twice in wednesday night ' s 3 - 1 win over bournemouth in the capital one cup quarter - final and is almost certain to lead the line against arsenal on sunday , given that mario bal ##ote ##lli is suspended . ra ##hee ##m sterling - l ##rb - right - rr ##b - scores liverpool ' s opening goal against bournemouth in the capital one cup . liverpool ' s steven ge ##rrard - l ##rb - left - rr ##b - holds off eun ##an o ' kane - l ##rb - right - rr ##b - in the capital one cup quarter - final match . the liverpool manager app ##lau ##ds his side from the touch ##line against bournemouth at gold ##san ##ds st

for decades they came to es ##po ##use their vile politics , but now locals in a town in germany have tricked neo - nazi marche ##rs into raising $ 10 , 000 to help them drop out of right - wing ex ##tre ##mism . the protesters gather annually in wu ##ns ##ied ##el in bavaria to visit the grave of rudolph hess , adolf hitler ' s deputy . this year , residents decided to donate $ 10 for every metre the marche ##rs walked . rights versus rights - l ##rb - rec ##ht ##s ge ##gen rec ##ht ##s - rr ##b - , the counter - protest by the locals , are dona ##ting their funds to exit germany . the programme aids people who want to escape fascist movements . scroll down for video . right - wing gather ##ers travel annually to wu ##ns ##ied ##el in bavaria to pay their respects to the grave of rudolph hess - but this year they un ##wi ##tting ##ly donated to a programme which helps people escape from ex ##tre ##mism . one organise ##r , fabian wi ##chman ##n , told german news agency d ##pa : ` we 

father christmas will be sitting pretty this christmas after swap ##ping his tired wooden sl ##edge for this high - tech ` super sl ##ei ##gh ' . the # 200 , 000 - l ##rb - $ 313 , 000 - rr ##b - carriage comes complete with built - in gps navigation , parking sensors and a chimney camera . it also features a bullet ##proof lex ##an poly ##carbon ##ate front window , a convertible roof and a built - in nose wipe ##r for santa ' s magical reindeer . pi ##mp my sl ##ei ##gh : the # 200 , 000 - l ##rb - $ 313 , 000 - rr ##b - carriage comes complete with built - in gps navigation , parking sensors and a chimney camera . and more presents could get delivered this year as rudolph and his friends will have access to hybrid - powered rocket booster ##s when they are running low on energy . other features include an e - reader mount for easy access to the naughty - and - nice list , a mist ##let ##oe air fresh ##ener and a cup warmer with hot chocolate . the concept ga ##dget sl ##ei ##gh 900 

In [27]:
print(c, m)

287113 511


In [18]:
m = 0
c = 0
for q in d.tgt:
    c+= 1
    m = max(len(q), m)


In [19]:
print(c, m)

287113 172


In [59]:
d.src_dict[999]

'!'

In [77]:

' '.join([d.src_dict[q.item()] for q in d[10]['source']])


"- l ##rb - cnn - rr ##b - he ' s a blue chip college basketball recruit . she ' s a high school freshman with down syndrome . at first glance trey moses and ellie meredith could n ' t be more different . but all that changed thursday when trey asked ellie to be his prom date . trey - - a star on eastern high school ' s basketball team in louisville , kentucky , who ' s headed to play college ball next year at ball state - - was originally going to take his girlfriend to eastern ' s prom . so why is he taking ellie instead ? ` ` she ' s great . . . she listen ##s and she ' s easy to talk to ' ' he said . trey made the prom - po ##sal - l ##rb - yes , that ' s what they are calling invites to prom these days - rr ##b - in the gym during ellie ' s p . e . class . tri ##na he ##lson , a teacher at eastern , alerted the school ' s newspaper staff to the prom - po ##sal and posted photos of trey and ellie on twitter that have gone viral . she was n ' t sur ##pr ##iste ##d by trey ' s action

In [83]:
eos_index = d.src_dict.eos_index
bos_index = d.src_dict.bos_index

In [90]:
d.src_dict[1012]

'.'

In [91]:
' '.join([d.src_dict[q.item()] for q in d[10]['target']])

"college - bound basketball star asks girl with down syndrome to high school prom . pictures of the two during the ` ` prom - po ##sal ' ' have gone viral . [SEP]"

In [94]:
' PAD '.join(['a', 'b'])

'a PAD b'

In [96]:
 x = torch.randn(10)

In [97]:
x

tensor([-0.8697,  1.9066,  0.3178, -0.2502,  0.4459, -0.7611, -2.1835, -0.5411,
         0.0074,  0.7384])

In [104]:
torch.cumsum(d[10]['source'].eq(1012),dim=0)

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  7,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 11,
        11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 13, 13, 13, 13, 13, 13, 

RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [109]:
mask = d[10]['source'].eq(1012).int()
mask


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [113]:
(torch.cumsum(mask, dim=0).type_as(mask) * mask).long() + 1012

tensor([1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1013, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1014, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1015, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1016, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1017, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1018, 1019, 1020, 1012, 1012, 1012, 1012, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 1012, 1012, 1021, 1012, 1012, 1012, 1012,
        1012, 1012, 1012, 1012, 1012, 10

In [20]:
from pytorch_transformers import BertTokenizer

In [23]:
bpe = BertTokenizer.from_pretrained('bert-base-uncased')
bpe.do_basic_tokenize = False

In [22]:
bpe._tokenize('[CLS] museum : anne frank died earlier than previously believed . [SEP] researchers re-examined archives and testimonies of survivors . [SEP] anne and older sister margot frank are believed to have died in february 1945 . [SEP]')

['[',
 '[UNK]',
 ']',
 'museum',
 ':',
 'anne',
 'frank',
 'died',
 'earlier',
 'than',
 'previously',
 'believed',
 '.',
 '[',
 '[UNK]',
 ']',
 'researchers',
 're',
 '-',
 'examined',
 'archives',
 'and',
 'test',
 '##imo',
 '##nies',
 'of',
 'survivors',
 '.',
 '[',
 '[UNK]',
 ']',
 'anne',
 'and',
 'older',
 'sister',
 'margot',
 'frank',
 'are',
 'believed',
 'to',
 'have',
 'died',
 'in',
 'february',
 '1945',
 '.',
 '[',
 '[UNK]',
 ']']

In [128]:
bpe.do_basic_tokenize = True
bpe._tokenize('[CLS] museum : anne frank died earlier than previously believed . [SEP] researchers re-examined archives and testimonies of survivors . [SEP] anne and older sister margot frank are believed to have died in february 1945 . [SEP]')

['[',
 '[UNK]',
 ']',
 'museum',
 ':',
 'anne',
 'frank',
 'died',
 'earlier',
 'than',
 'previously',
 'believed',
 '.',
 '[',
 '[UNK]',
 ']',
 'researchers',
 're',
 '-',
 'examined',
 'archives',
 'and',
 'test',
 '##imo',
 '##nies',
 'of',
 'survivors',
 '.',
 '[',
 '[UNK]',
 ']',
 'anne',
 'and',
 'older',
 'sister',
 'margot',
 'frank',
 'are',
 'believed',
 'to',
 'have',
 'died',
 'in',
 'february',
 '1945',
 '.',
 '[',
 '[UNK]',
 ']']

In [134]:
pad_idx = 10
eos_idx = 20

sent = torch.tensor([10, 10, 10, 10, 10, 5, 6, 7, 20, 8, 9, 4, 20, 30, 30, 30, 20])

In [163]:
sent

tensor([10, 10, 10, 10, 10,  5,  6,  7, 20,  8,  9,  4, 20, 30, 30, 30, 20])

In [160]:
mask = sent.ne(pad_idx)
keep = sent.eq(pad_idx)

In [162]:
mask

tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [138]:
(torch.cumsum(mask, dim=0).type_as(mask) * mask).long() + pad_idx

tensor([10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

tensor([ 0,  0,  0,  0,  0,  5,  6,  7, 20,  8,  9,  4, 20, 30, 30, 30, 20],
       dtype=torch.int32)

In [161]:
pos = (torch.cumsum((sent.type_as(mask) * mask).eq(eos_idx), dim=0).t + pad_idx + mask).long()

RuntimeError: expected type torch.LongTensor but got torch.IntTensor

In [157]:
mask + pos

tensor([10, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14],
       dtype=torch.int32)

In [166]:
def make_sentence_positions(tensor, padding_idx, eos_idx):
    mask = tensor.ne(padding_idx).int()
    return (
        torch.cumsum((tensor.type_as(mask) * mask).eq(eos_idx), dim=0).type_as(mask) + mask 
    ).long() + padding_idx




In [167]:
make_sentence_positions(sent, pad_idx, eos_idx)

tensor([10, 10, 10, 10, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14])

In [35]:
src = torch.tensor([5, 16, 22, 99, 6, 7, 8, 13, 5, 61, 9, 0, 3, 3, 5, 6, 7, 9, 10])
tgt = torch.tensor([9, 33, 71, 81, 3, 3, 4, 15, 6, 33, 2, 3, 4, 5, 6, 5, 6, 6, 10])


In [42]:
def intersect1d(tensor1, tensor2):
    aux = torch.cat((tensor1, tensor2))
    aux = aux.sort()[0]
    return aux[:-1][(aux[1:] == aux[:-1]).data]


In [44]:
u = torch.unique(intersect1d(src, tgt))

In [46]:
import numpy as np

In [49]:
xy, x_ind, y_ind = np.intersect1d(src, tgt, return_indices=True)

In [54]:
torch.index_select(src, 0, torch.tensor(x_ind))

tensor([ 3,  5,  6,  9, 10])

In [73]:
src - 

tensor([ 5, 16, 22, 99,  6,  7,  8, 13,  5, 61,  9,  0,  3,  3,  5,  6,  7,  9,
        10])

In [70]:
        positions = np.arange(0, 1000)
        masked_pos = []
        for i in range(1, 1000, 64):
            block = positions[i: i + 64]
            masked_len = int(len(block) * 0.15)
            masked_block_start = np.random.choice(block[:-int(masked_len) + 1], 1)[0]
            masked_pos.extend(positions[masked_block_start : masked_block_start + masked_len])
        print(masked_pos)

[55, 56, 57, 58, 59, 60, 61, 62, 63, 117, 118, 119, 120, 121, 122, 123, 124, 125, 179, 180, 181, 182, 183, 184, 185, 186, 187, 236, 237, 238, 239, 240, 241, 242, 243, 244, 283, 284, 285, 286, 287, 288, 289, 290, 291, 369, 370, 371, 372, 373, 374, 375, 376, 377, 404, 405, 406, 407, 408, 409, 410, 411, 412, 470, 471, 472, 473, 474, 475, 476, 477, 478, 514, 515, 516, 517, 518, 519, 520, 521, 522, 595, 596, 597, 598, 599, 600, 601, 602, 603, 695, 696, 697, 698, 699, 700, 701, 702, 703, 742, 743, 744, 745, 746, 747, 748, 749, 750, 772, 773, 774, 775, 776, 777, 778, 779, 780, 881, 882, 883, 884, 885, 886, 887, 888, 889, 940, 941, 942, 943, 944, 945, 946, 947, 948, 971, 972, 973, 974, 975]


In [64]:
masked_pos

array([], dtype=float64)

In [74]:
d.src_dict[999]

NameError: name 'd' is not defined

In [ ]:
Some tests

In [22]:
# sequence = B x T

def create_segments(sequence, segment_tokens, max_segments=4):
    bsz, T = sequence.shape
    segments = torch.zeros_like(sequence)
    
    for segment_token in segment_tokens:
        segments += sequence.eq(segment_token).type_as(segments)
        
    segments = torch.cumsum(segments, dim=1)
    narrowed = torch.narrow(segments, 1, 1, T - 1)
    append = torch.zeros((bsz, 1)).type_as(narrowed)

    return torch.cat((append, narrowed), 1).clamp(0, max_segments - 1)

In [23]:
import torch

bsz = 16
T = 100
seq = torch.randint(100, (bsz, T))
seq = create_segments(seq, [5,10, 15, 33])
                

In [24]:
seq.shape

torch.Size([16, 100])

In [25]:
seq

tensor([[0, 0, 1,  ..., 2, 2, 2],
        [0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 3, 3, 3],
        ...,
        [0, 0, 0,  ..., 2, 2, 3],
        [0, 0, 0,  ..., 3, 3, 3],
        [0, 0, 0,  ..., 3, 3, 3]])

In [28]:
a = [1,2,3,4,5]

a[:510]

[1, 2, 3]